customhost = "aws2project2.c4aetroxrbdj.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "aws2project2"
custombucket = "aws2project2"
customregion = " ap-south-1"
