customhost = "project2aws2.c4aetroxrbdj.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "project2aws2"
custombucket = "project2aws2"
customregion = " ap-south-1"
